
language: cpp

branches:
  only:
    - master

jobs:
  fast_finish: true
  include:
    - os: linux
      name: X86_64
      dist: bionic
    - os: linux
      name: S390X
      arch: s390x
      dist: bionic
    - os: linux
      name: PPC64
      arch: ppc64le
      dist: bionic
    - os: linux
      name: ARM64
      arch: arm64
      dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:beineri/opt-qt-5.12.0-bionic"
    packages:
       - python3-pip
       - python3-setuptools
       - ninja-build
       - qt512base
       - libgl1-mesa-dev

env:
  - INSTALL_PREFIX=$TRAVIS_BUILD_DIR/radare2-prefix

install:
  - pip3 install meson
  - git clone --depth 1 https://github.com/radareorg/radare2
  - cd radare2 && mkdir build && cd build
  - meson --prefix="$INSTALL_PREFIX" ..
  - ninja
  - ninja install
  - cd ../..
  - git clone --depth 1 https://github.com/radareorg/cutter

script:
  - mkdir build && cd build
  - cmake
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="$TRAVIS_BUILD_DIR/radare2-prefix;/opt/qt512"
      -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX"
      -DBUILD_CUTTER_PLUGIN=ON
      -DCUTTER_SOURCE_DIR="$TRAVIS_BUILD_DIR/cutter"
      -DBUILD_SLEIGH_PLUGIN=ON
      ..
  - make -j4
  - make install
  - export LD_LIBRARY_PATH="$INSTALL_PREFIX/lib:$INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
  - export PATH="$INSTALL_PREFIX/bin:$PATH"
  - export R2_LIBR_PLUGINS="$INSTALL_PREFIX/share/radare2/plugins"
  - cd ../test
  - make

